from cozy_tui.style import Style

CLASSIC = {
    "default": {
        "style": Style(fg="white", bg="black"),
        "accent": "bright_cyan",
        "muted": "bright_black",
        "info": "bright_cyan",
        "success": "bright_green",
        "warning": "bright_yellow",
        "error": "bright_red",
        "selection_fg": "black",
        "selection_bg": "white",
    },
    "monochromatic": {
        "style": Style(fg="white", bg="black"),
        "accent": "bright_white",
        "muted": "bright_black",
        "info": "bright_black",
        "success": "white",
        "warning": "bright_white",
        "error": "bright_white",
        "selection_fg": "black",
        "selection_bg": "white",
    },
    "retro": {
        "style": Style(fg="green", bg="black"),
        "accent": "bright_green",
        "muted": "green",
        "info": "bright_green",
        "success": "bright_green",
        "warning": "yellow",
        "error": "red",
        "selection_fg": "black",
        "selection_bg": "green",
    },
    "amber": {
        "style": Style(fg="yellow", bg="black"),
        "accent": "bright_yellow",
        "muted": "yellow",
        "info": "yellow",
        "success": "bright_yellow",
        "warning": "bright_yellow",
        "error": "bright_red",
        "selection_fg": "black",
        "selection_bg": "yellow",
    },
    "gameboy": {
        "style": Style(fg="#0f380f", bg="#9bbc0f"),
        "accent": "#306230",
        "muted": "#8bac0f",
        "info": "#306230",
        "success": "#306230",
        "warning": "#8bac0f",
        "error": "#0f380f",
        "selection_fg": "#9bbc0f",
        "selection_bg": "#306230",
    },
}

NATURE = {
    "ocean": {
        "style": Style(fg="white", bg="#071a2b"),
        "accent": "bright_cyan",
        "muted": "blue",
        "info": "cyan",
        "success": "bright_green",
        "warning": "bright_yellow",
        "error": "bright_red",
        "selection_fg": "black",
        "selection_bg": "bright_cyan",
    },
    "forest": {
        "style": Style(fg="white", bg="#061706"),
        "accent": "bright_green",
        "muted": "green",
        "info": "bright_cyan",
        "success": "bright_green",
        "warning": "yellow",
        "error": "bright_red",
        "selection_fg": "black",
        "selection_bg": "bright_green",
    },
    "desert": {
        "style": Style(fg="#f2d8b5", bg="#3a2414"),
        "accent": "#d4a017",
        "muted": "#8f6a44",
        "info": "#87ceeb",
        "success": "#98fb98",
        "warning": "#ffd700",
        "error": "#ff6347",
        "selection_fg": "#3a2414",
        "selection_bg": "#d4a017",
    },
    "aurora": {
        "style": Style(fg="#e8f5ff", bg="#10192c"),
        "accent": "#00d4ff",
        "muted": "#4d648d",
        "info": "#7df9ff",
        "success": "#00ff9c",
        "warning": "#ffe066",
        "error": "#ff6b6b",
        "selection_fg": "#10192c",
        "selection_bg": "#00d4ff",
    },
    "mint": {
        "style": Style(fg="#f4fff8", bg="#123524"),
        "accent": "#52d681",
        "muted": "#5f8d6d",
        "info": "#7fe7dc",
        "success": "#52d681",
        "warning": "#ffe066",
        "error": "#ff6b6b",
        "selection_fg": "#123524",
        "selection_bg": "#52d681",
    },
    "evergreen": {
        "style": Style(fg="#eaf7ef", bg="#0b1f14"),
        "accent": "#2ecc71",
        "muted": "#4e7a60",
        "info": "#4dd0e1",
        "success": "#66bb6a",
        "warning": "#fbc02d",
        "error": "#ef5350",
        "selection_fg": "#0b1f14",
        "selection_bg": "#2ecc71",
    },
}

DARK = {
    "night": {
        "style": Style(fg="#d8dee9", bg="#0b0f19"),
        "accent": "#88c0d0",
        "muted": "#4c566a",
        "info": "#81a1c1",
        "success": "#a3be8c",
        "warning": "#ebcb8b",
        "error": "#bf616a",
        "selection_fg": "#0b0f19",
        "selection_bg": "#88c0d0",
    },
    "midnight": {
        "style": Style(fg="#f5f5f5", bg="#050505"),
        "accent": "#4fc3f7",
        "muted": "#616161",
        "info": "#29b6f6",
        "success": "#66bb6a",
        "warning": "#ffee58",
        "error": "#ef5350",
        "selection_fg": "#050505",
        "selection_bg": "#4fc3f7",
    },
    "dracula": {
        "style": Style(fg="#f8f8f2", bg="#282a36"),
        "accent": "#bd93f9",
        "muted": "#6272a4",
        "info": "#8be9fd",
        "success": "#50fa7b",
        "warning": "#f1fa8c",
        "error": "#ff5555",
        "selection_fg": "#282a36",
        "selection_bg": "#bd93f9",
    },
    "cyberpunk": {
        "style": Style(fg="white", bg="#090014"),
        "accent": "bright_magenta",
        "muted": "bright_black",
        "info": "bright_cyan",
        "success": "bright_green",
        "warning": "bright_yellow",
        "error": "bright_red",
        "selection_fg": "black",
        "selection_bg": "bright_magenta",
    },
    "royal": {
        "style": Style(fg="white", bg="#100020"),
        "accent": "bright_magenta",
        "muted": "magenta",
        "info": "bright_cyan",
        "success": "bright_green",
        "warning": "bright_yellow",
        "error": "bright_red",
        "selection_fg": "white",
        "selection_bg": "magenta",
    },
    "nord": {
        "style": Style(fg="#d8dee9", bg="#2e3440"),
        "accent": "#88c0d0",
        "muted": "#616e88",
        "info": "#81a1c1",
        "success": "#a3be8c",
        "warning": "#ebcb8b",
        "error": "#bf616a",
        "selection_fg": "#2e3440",
        "selection_bg": "#88c0d0",
    },
    "violet": {
        "style": Style(fg="#f4f0ff", bg="#170b2d"),
        "accent": "#9d4edd",
        "muted": "#5a3d7a",
        "info": "#7bdff2",
        "success": "#80ed99",
        "warning": "#ffd166",
        "error": "#ff5d73",
        "selection_fg": "#170b2d",
        "selection_bg": "#9d4edd",
    },
}

WARM = {
    "parchment": {
        "style": Style(fg="#4a3728", bg="#f8f1e5"),
        "accent": "#8b5e3c",
        "muted": "#8a7967",
        "info": "#5c7cfa",
        "success": "#4caf50",
        "warning": "#ff9800",
        "error": "#c62828",
        "selection_fg": "#f8f1e5",
        "selection_bg": "#8b5e3c",
    },
    "sunset": {
        "style": Style(fg="white", bg="#1a0f1f"),
        "accent": "bright_yellow",
        "muted": "magenta",
        "info": "bright_cyan",
        "success": "bright_green",
        "warning": "yellow",
        "error": "bright_red",
        "selection_fg": "black",
        "selection_bg": "bright_yellow",
    },
    "coffee": {
        "style": Style(fg="#f5e6d3", bg="#1b120b"),
        "accent": "#d2691e",
        "muted": "#8b6f47",
        "info": "#87ceeb",
        "success": "#98fb98",
        "warning": "#ffd700",
        "error": "#ff6347",
        "selection_fg": "black",
        "selection_bg": "#d2691e",
    },
    "ember": {
        "style": Style(fg="bright_yellow", bg="black"),
        "accent": "bright_red",
        "muted": "yellow",
        "info": "bright_yellow",
        "success": "bright_green",
        "warning": "bright_yellow",
        "error": "red",
        "selection_fg": "black",
        "selection_bg": "bright_yellow",
    },
    "lava": {
        "style": Style(fg="#fff2e0", bg="#180909"),
        "accent": "#ff6b35",
        "muted": "#8b3a2f",
        "info": "#ffb347",
        "success": "#98fb98",
        "warning": "#ffd700",
        "error": "#ff3b30",
        "selection_fg": "#180909",
        "selection_bg": "#ff6b35",
    },
}

COLD = {
    "arctic": {
        "style": Style(fg="#ffffff", bg="#dceefb"),
        "accent": "#00acc1",
        "muted": "#78909c",
        "info": "#26c6da",
        "success": "#66bb6a",
        "warning": "#ffca28",
        "error": "#ef5350",
        "selection_fg": "#dceefb",
        "selection_bg": "#00acc1",
    },
    "solarized": {
        "style": Style(fg="#839496", bg="#002b36"),
        "accent": "#268bd2",
        "muted": "#586e75",
        "info": "#2aa198",
        "success": "#859900",
        "warning": "#b58900",
        "error": "#dc322f",
        "selection_fg": "#002b36",
        "selection_bg": "#93a1a1",
    },
    "ice": {
        "style": Style(fg="white", bg="#101820"),
        "accent": "bright_cyan",
        "muted": "bright_black",
        "info": "cyan",
        "success": "bright_green",
        "warning": "bright_yellow",
        "error": "bright_red",
        "selection_fg": "black",
        "selection_bg": "bright_cyan",
    },
}

FUN = {
    "toxic": {
        "style": Style(fg="white", bg="#080d08"),
        "accent": "bright_green",
        "muted": "bright_black",
        "info": "bright_magenta",
        "success": "bright_green",
        "warning": "bright_yellow",
        "error": "bright_red",
        "selection_fg": "black",
        "selection_bg": "bright_green",
    },
    "sakura": {
        "style": Style(fg="#ffeef8", bg="#2b1623"),
        "accent": "#ff79c6",
        "muted": "#a66a89",
        "info": "#8be9fd",
        "success": "#50fa7b",
        "warning": "#f1fa8c",
        "error": "#ff5555",
        "selection_fg": "#2b1623",
        "selection_bg": "#ff79c6",
    },
    "strawberry": {
        "style": Style(fg="#fff5f7", bg="#2a0d16"),
        "accent": "#ff4d6d",
        "muted": "#a53860",
        "info": "#8be9fd",
        "success": "#50fa7b",
        "warning": "#ffd166",
        "error": "#ff1744",
        "selection_fg": "#2a0d16",
        "selection_bg": "#ff4d6d",
    },
    "pastel": {
        "style": Style(fg="#f8f8ff", bg="#30343f"),
        "accent": "#b388ff",
        "muted": "#9fa8b8",
        "info": "#80d8ff",
        "success": "#69f0ae",
        "warning": "#ffe082",
        "error": "#ff8a80",
        "selection_fg": "#30343f",
        "selection_bg": "#b388ff",
    },
    "rainbow": {
        "style": Style(fg="white", bg="black"),
        "accent": "bright_magenta",
        "muted": "bright_black",
        "info": "bright_cyan",
        "success": "bright_green",
        "warning": "bright_yellow",
        "error": "bright_red",
        "selection_fg": "black",
        "selection_bg": "bright_magenta",
    },
    "grape": {
        "style": Style(fg="white", bg="#160d24"),
        "accent": "bright_magenta",
        "muted": "magenta",
        "info": "bright_cyan",
        "success": "bright_green",
        "warning": "bright_yellow",
        "error": "bright_red",
        "selection_fg": "white",
        "selection_bg": "magenta",
    },
    "neon": {
        "style": Style(fg="white", bg="black"),
        "accent": "bright_cyan",
        "muted": "bright_black",
        "info": "bright_blue",
        "success": "bright_green",
        "warning": "bright_yellow",
        "error": "bright_magenta",
        "selection_fg": "black",
        "selection_bg": "bright_cyan",
    },
    "hacker": {
        "style": Style(fg="green", bg="black"),
        "accent": "bright_green",
        "muted": "green",
        "info": "bright_green",
        "success": "bright_green",
        "warning": "yellow",
        "error": "bright_red",
        "selection_fg": "black",
        "selection_bg": "bright_green",
    },
    "matrix": {
        "style": Style(fg="#00ff41", bg="#000000"),
        "accent": "#00ff00",
        "muted": "#008f11",
        "info": "#66ff99",
        "success": "#00ff41",
        "warning": "#ccff33",
        "error": "#ff4444",
        "selection_fg": "#000000",
        "selection_bg": "#00ff41",
    },
}

# theme.py looks presets up by name (PRESETS[mode], mode not in PRESETS,
# tuple(PRESETS) for Theme.MODES), so this has to be one flat mapping --
# the category dicts above are just for organizing this file, not the
# shape callers actually need.
PRESETS = {**CLASSIC, **NATURE, **DARK, **COLD, **WARM, **FUN}

# display category name -> mode names in it, derived from the dicts above so
# this can't drift out of sync as presets are added/moved between categories.
# Consumed by cozy_tui.themes (the `python -m cozy_tui.themes` showcase) to
# group the ever-growing preset list instead of dumping it as one flat list.
CATEGORIES = {
    "Classic": list(CLASSIC),
    "Nature": list(NATURE),
    "Dark": list(DARK),
    "Cold": list(COLD),
    "Warm": list(WARM),
    "Fun": list(FUN),
}
